services:
  vkr:
    image: ghcr.io/mrtnvgr/vkreborn
    restart: always
    env_file: .env
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: vkreborn
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
