[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[project]
name = "VKReborn"
version = "never-ending"
dependencies = ["vkbottle"]

[project.optional-dependencies]
test = [
	"black",
	"flake8",
	"flake8-isort",
]

[flake8]
max-line-length = 98
ignore = ["F403", "F405"]
