[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[project]
name = "vkreborn"
version = "0.0.0"
dependencies = ["vkbottle"]

[project.scripts]
vkreborn = "vkreborn:__main__.py"

[project.optional-dependencies]
test = [
	"black",
	"flake8",
	"flake8-isort",
]

[flake8]
max-line-length = 98
ignore = ["F403", "F405"]
