[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]

[project]
name = "vkreborn"
version = "0.0.0"
dependencies = [
	"vkbottle",
	"loguru",
	"SQLAlchemy",
	"asyncpg",
]

[project.scripts]
vkreborn = "vkreborn.__main__:main"

[project.optional-dependencies]
test = [
	"black",
	"flakeheaven",
]

[tool.flakeheaven]
format = "grouped"
max_line_length = 98
pyflakes = ["+*", "-F403", "-F405"]
