from os import environ

VKTOKEN = environ["VKTOKEN"]


POSTGRES_HOST = environ.get("POSTGRES_HOST", default="localhost")
POSTGRES_PORT = environ.get("POSTGRES_PORT", default=5432)
POSTGRES_DB = environ.get("POSTGRES_DB", default="vkreborn")
POSTGRES_USER = environ.get("POSTGRES_USER", default="postgres")

POSTGRES_PASSWORD = environ["POSTGRES_PASSWORD"]


SQLALCHEMY_DATABASE_URI = "postgresql+asyncpg://"
SQLALCHEMY_DATABASE_URI += f"{POSTGRES_USER}:{POSTGRES_PASSWORD}"
SQLALCHEMY_DATABASE_URI += f"@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"

SQLALCHEMY_TRACK_MODIFICATIONS = False


WALLHAVEN_API_KEY = environ.get("WALLHAVEN_API_KEY", None)


FX_NIGHTCORE_SPEED = environ.get("FX_NIGHTCORE_SPEED", 1.35)
FX_SOFTNIGHTCORE_SPEED = environ.get("FX_SOFTNIGHTCORE_SPEED", 1.17)
FX_DAYCORE_SPEED = environ.get("FX_DAYCORE_SPEED", 0.70)
FX_SOFTDAYCORE_SPEED = environ.get("FX_SOFTDAYCORE_SPEED", 0.85)

FX_BASSBOOST_GAIN = environ.get("FX_BASSBOOST_GAIN", 7.8)
FX_BASSCUT_GAIN = environ.get("FX_BASSCUT_GAIN", -7.8)
