name: Dependabot auto-merge

on: pull_request

permissions: write-all

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: asottile/workflows/.github/actions/fast-checkout@v1.4.1

      - name: Merge pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          gh pr merge $PR_NUMBER --squash --delete-branch --auto
